name: PyOPF
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=22.2.0
  - beautifulsoup4=4.11.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cctools=973.0.1
  - cctools_osx-arm64=973.0.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - colorlog=6.7.0
  - conda=23.1.0
  - conda-build=3.23.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=39.0.2
  - filelock=3.9.0
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.12.0
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - ld64=609
  - ld64_osx-arm64=609
  - libarchive=3.6.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=15.0.7
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.2
  - mpc=1.3.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - ncurses=6.3
  - networkx=3.0
  - numpy=1.24.2
  - openssl=3.0.8
  - packaging=23.0
  - patch=2.7.6
  - pip=23.0.1
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - psutil=5.9.4
  - py-lief=0.12.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pyomo=6.4.4
  - pyopenssl=23.0.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.9
  - python-libarchive-c=4.0
  - python_abi=3.10
  - pytz=2022.7.1
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scipy=1.10.0
  - setuptools=67.4.0
  - sigtool=0.1.3
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sympy=1.11.1
  - tapi=1100.0.11
  - termcolor=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.15.0
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - commonmark=
      - exceptiongroup=
      - iniconfig=
      - pygments=
      - pygount=
      - pytest=
      - rich=
      - tomli=
