name: PyOPF
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - attrs=22.2.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - colorlog=6.7.0
  - conda=23.1.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=39.0.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - jsonschema=4.17.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - mpc=1.3.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - ncurses=6.3
  - networkx=3.0
  - numpy=1.24.2
  - openssl=3.0.8
  - packaging=23.0
  - pip=23.0
  - pkgutil-resolve-name=1.3.10
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyomo=6.4.4
  - pyopenssl=23.0.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.9
  - python_abi=3.10
  - readline=8.1.2
  - requests=2.28.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scipy=1.10.0
  - setuptools=67.1.0
  - sympy=1.11.1
  - termcolor=2.2.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - versioneer=0.28
  - wheel=0.38.4
  - xz=5.2.6
  - zipp=3.13.0
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - exceptiongroup
      - iniconfig
      - pytest
      - tomli
